### ISSUE TITLE
[EMail] WebDav Import/Synchronize framework

### ISSUE THREAD

**Issue by fb71** [fb71/areca#14]
**Email** 
  - [ ] read INBOX (or another folder); up to LIMIT message count
  - [ ] check/create existing Message and person/contact Anchors
  
**Framework** (*areca.systemservice.client*)
  - [x] concurrent API/framework (webdav visitor?)
  - [x] allow simple filter/process of webdav hierarchy (visitor?)

**Todo**
  - [ ] strip contextPath

**Comment by fb71** [comment]
Deprecated in favour of #15.
